linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - decorder
    - depguard
    - gofmt
    - goimports
    - gosec
    - revive
    - unconvert
    - misspell
    - typecheck
    - durationcheck
    - forbidigo
    - gci
    - whitespace
    - gofumpt
    - gocritic

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/milvus-io)
      - prefix(github.com/zilliztech)
    custom-order: true
  gofumpt:
    # lang-version: "1.21"
    module-path: github.com/zilliztech
  goimports:
    local-prefixes: github.com/zilliztech
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # Allow list
      - name: context-as-argument
        severity: warning
        disabled: false
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: datarace
        severity: warning
        disabled: false
      - name: duplicated-imports
        severity: warning
        disabled: false
      - name: waitgroup-by-value
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
        arguments:
          - "preserveScope"
      - name: range-val-in-closure
        severity: warning
        disabled: false
      - name: range-val-address
        severity: warning
        disabled: false
      - name: string-of-int
        severity: warning
        disabled: false
  misspell:
    locale: US

run:
  go: "1.24.1"
  skip-dirs:
    - pb/*
    - mocks/*
    - tool/*

issues:
  exclude-use-default: false
  exclude:
    - should have a package comment
    - should have comment
    - should be of the form
    - should not use dot imports
    - which can be annoying to use
    - is not allowed from list 'Main'
    - param.FieldName is deprecated
    - G103
    - G102
    - G404
    - G201
    - G114
    - SA1019
    - has no field or method
    - G115
  # Maximum issue count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0