#Configuration File for CodeCov
codecov:
  notify:
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 80% #Allow the coverage to drop by threshold%, and posting a success status.
        branches:
          - main
    patch:
      default:
        target: 80%
        threshold: 0%
        branches:
          - main
        if_ci_failed: error #success, failure, error, ignore

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  branches: # branch names that can post comment
    - main

ignore:
  - "LICENSES"
  - ".git"
  - "*.yml"
  - "*.md"
  - "docs/.*"
  - "**/*.pb.go"
  - "examples/*"
  - "tests/*"
  - "**/mocks/*"
  - "*_gen.go"
  - "server/main/*"
  - "server/tool/*"
  - "server/configs/*"