services:
  milvus-cdc:
    container_name: milvus-cdc
    image: milvusdb/milvus-cdc:latest
    tty: true
    ports:
      - "8444:8444"
    volumes:
      - type: bind
        source: ./cdc.yaml
        target: /app/configs/cdc.yaml
        read_only: true