cluster:
  enabled: true

log:
  level: debug

image:
  all:
    repository: fubangzilliz/milvus-dev
    tag: cdc-8c1cd0c-20230926
    pullPolicy: IfNotPresent
standalone:
  resources:
    limits:
      cpu: 8
      memory: 16Gi
    requests:
      cpu: 4
      memory: 8Gi

kafka:
  enabled: false
  name: kafka
  replicaCount: 3
  defaultReplicationFactor: 2

etcd:
  replicaCount: 3
  image:
    repository: milvusdb/etcd
    tag: 3.5.5-r2  
# minio:
#   mode: standalone
pulsar:
  enabled: true

extraConfigFiles:
  user.yaml: |+
    mq:
      type: pulsar
    common:
      isBackupInstance: true