{
 "title": "cdc",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": { "query": "label_values(instance)" } },
   { "name": "request_type", "label": "request type", "query": { "query": "label_values(request_type)" } },
   { "name": "task_id", "label": "task id", "query": { "query": "label_values(task_id)" } },
   { "name": "channel_name", "label": "channel name", "query": { "query": "label_values(vchannel_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Task",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "milvus_cdc_task_num{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "milvus_cdc_request_total{request_status=\"total\", instance=~\"$instance\"}",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "Request Success",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "milvus_cdc_request_total{request_status=\"success\", instance=~\"$instance\"}",
     "legendFormat": "{{request_type}}"
    }
   ]
  },
  {
   "title": "task num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "milvus_cdc_task_num{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{task_state}}"
    }
   ]
  },
  {
   "title": "task state",
   "type": "timeseries",
   "description": "0: Initial; 1: Running; 2: Paused; -1: Deleted",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "milvus_cdc_task_state{instance=~\"$instance\", task_id=~\"$task_id\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "milvus_cdc_request_total{instance=~\"$instance\", request_type=~\"$request_type\"}",
     "legendFormat": "{{request_type}}-{{request_status}}"
    }
   ]
  },
  {
   "title": "request latency",
   "type": "timeseries",
   "description": "The 99th percentile and average request latency over the last 1 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le, instance, request_type) (rate(milvus_cdc_request_latency_bucket{instance=~\"$instance\", request_type=~\"$request_type\"}[1m])))",
     "legendFormat": "p99-{{instance}}-{{request_type}}"
    },
    {
     "expr": "sum(increase(milvus_cdc_request_latency_sum{instance=~\"$instance\", request_type=~\"$request_type\"}[1m])) by(instance, request_type) / sum(increase(milvus_cdc_request_latency_count{instance=~\"$instance\", request_type=~\"$request_type\"}[1m])) by(instance, request_type)",
     "legendFormat": "avg-{{instance}}-{{request_type}}"
    }
   ]
  },
  {
   "title": "replicate data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(milvus_cdc_replicate_data_size{instance=~\"$instance\"}[1m])/60) by (task_id, vchannel_name, op_type)",
     "legendFormat": "{{task_id}}-{{vchannel_name}}-{{op_type}}"
    }
   ]
  },
  {
   "title": "replicate tt lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "milvus_cdc_replicate_tt_lag{instance=~\"$instance\", task_id=~\"$task_id\", vchannel_name=~\"$channel_name\"}",
     "legendFormat": "{{task_id}}-{{vchannel_name}}-{{op_type}}"
    }
   ]
  },
  {
   "title": "api execute count",
   "type": "timeseries",
   "description": "the counter of executing target api",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "milvus_cdc_api_execute_total{instance=~\"$instance\", task_id=~\"$task_id\"}",
     "legendFormat": "{{task_id}}-{{api_type}}"
    }
   ]
  }
 ]
}