// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/zilliztech/milvus-cdc/core/api"

	mock "github.com/stretchr/testify/mock"

	msgpb "github.com/milvus-io/milvus-proto/go-api/v2/msgpb"

	msgstream "github.com/milvus-io/milvus/pkg/mq/msgstream"

	pb "github.com/zilliztech/milvus-cdc/core/pb"
)

// ChannelManager is an autogenerated mock type for the ChannelManager type
type ChannelManager struct {
	mock.Mock
}

type ChannelManager_Expecter struct {
	mock *mock.Mock
}

func (_m *ChannelManager) EXPECT() *ChannelManager_Expecter {
	return &ChannelManager_Expecter{mock: &_m.Mock}
}

// AddPartition provides a mock function with given fields: ctx, collectionInfo, partitionInfo
func (_m *ChannelManager) AddPartition(ctx context.Context, collectionInfo *pb.CollectionInfo, partitionInfo *pb.PartitionInfo) error {
	ret := _m.Called(ctx, collectionInfo, partitionInfo)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CollectionInfo, *pb.PartitionInfo) error); ok {
		r0 = rf(ctx, collectionInfo, partitionInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelManager_AddPartition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPartition'
type ChannelManager_AddPartition_Call struct {
	*mock.Call
}

// AddPartition is a helper method to define mock.On call
//  - ctx context.Context
//  - collectionInfo *pb.CollectionInfo
//  - partitionInfo *pb.PartitionInfo
func (_e *ChannelManager_Expecter) AddPartition(ctx interface{}, collectionInfo interface{}, partitionInfo interface{}) *ChannelManager_AddPartition_Call {
	return &ChannelManager_AddPartition_Call{Call: _e.mock.On("AddPartition", ctx, collectionInfo, partitionInfo)}
}

func (_c *ChannelManager_AddPartition_Call) Run(run func(ctx context.Context, collectionInfo *pb.CollectionInfo, partitionInfo *pb.PartitionInfo)) *ChannelManager_AddPartition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pb.CollectionInfo), args[2].(*pb.PartitionInfo))
	})
	return _c
}

func (_c *ChannelManager_AddPartition_Call) Return(_a0 error) *ChannelManager_AddPartition_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_AddPartition_Call) RunAndReturn(run func(context.Context, *pb.CollectionInfo, *pb.PartitionInfo) error) *ChannelManager_AddPartition_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelChan provides a mock function with given fields:
func (_m *ChannelManager) GetChannelChan() <-chan string {
	ret := _m.Called()

	var r0 <-chan string
	if rf, ok := ret.Get(0).(func() <-chan string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan string)
		}
	}

	return r0
}

// ChannelManager_GetChannelChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelChan'
type ChannelManager_GetChannelChan_Call struct {
	*mock.Call
}

// GetChannelChan is a helper method to define mock.On call
func (_e *ChannelManager_Expecter) GetChannelChan() *ChannelManager_GetChannelChan_Call {
	return &ChannelManager_GetChannelChan_Call{Call: _e.mock.On("GetChannelChan")}
}

func (_c *ChannelManager_GetChannelChan_Call) Run(run func()) *ChannelManager_GetChannelChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelManager_GetChannelChan_Call) Return(_a0 <-chan string) *ChannelManager_GetChannelChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_GetChannelChan_Call) RunAndReturn(run func() <-chan string) *ChannelManager_GetChannelChan_Call {
	_c.Call.Return(run)
	return _c
}

// GetEventChan provides a mock function with given fields:
func (_m *ChannelManager) GetEventChan() <-chan *api.ReplicateAPIEvent {
	ret := _m.Called()

	var r0 <-chan *api.ReplicateAPIEvent
	if rf, ok := ret.Get(0).(func() <-chan *api.ReplicateAPIEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *api.ReplicateAPIEvent)
		}
	}

	return r0
}

// ChannelManager_GetEventChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEventChan'
type ChannelManager_GetEventChan_Call struct {
	*mock.Call
}

// GetEventChan is a helper method to define mock.On call
func (_e *ChannelManager_Expecter) GetEventChan() *ChannelManager_GetEventChan_Call {
	return &ChannelManager_GetEventChan_Call{Call: _e.mock.On("GetEventChan")}
}

func (_c *ChannelManager_GetEventChan_Call) Run(run func()) *ChannelManager_GetEventChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ChannelManager_GetEventChan_Call) Return(_a0 <-chan *api.ReplicateAPIEvent) *ChannelManager_GetEventChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_GetEventChan_Call) RunAndReturn(run func() <-chan *api.ReplicateAPIEvent) *ChannelManager_GetEventChan_Call {
	_c.Call.Return(run)
	return _c
}

// GetMsgChan provides a mock function with given fields: pChannel
func (_m *ChannelManager) GetMsgChan(pChannel string) <-chan *msgstream.MsgPack {
	ret := _m.Called(pChannel)

	var r0 <-chan *msgstream.MsgPack
	if rf, ok := ret.Get(0).(func(string) <-chan *msgstream.MsgPack); ok {
		r0 = rf(pChannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *msgstream.MsgPack)
		}
	}

	return r0
}

// ChannelManager_GetMsgChan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMsgChan'
type ChannelManager_GetMsgChan_Call struct {
	*mock.Call
}

// GetMsgChan is a helper method to define mock.On call
//  - pChannel string
func (_e *ChannelManager_Expecter) GetMsgChan(pChannel interface{}) *ChannelManager_GetMsgChan_Call {
	return &ChannelManager_GetMsgChan_Call{Call: _e.mock.On("GetMsgChan", pChannel)}
}

func (_c *ChannelManager_GetMsgChan_Call) Run(run func(pChannel string)) *ChannelManager_GetMsgChan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ChannelManager_GetMsgChan_Call) Return(_a0 <-chan *msgstream.MsgPack) *ChannelManager_GetMsgChan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_GetMsgChan_Call) RunAndReturn(run func(string) <-chan *msgstream.MsgPack) *ChannelManager_GetMsgChan_Call {
	_c.Call.Return(run)
	return _c
}

// StartReadCollection provides a mock function with given fields: ctx, info, seekPositions
func (_m *ChannelManager) StartReadCollection(ctx context.Context, info *pb.CollectionInfo, seekPositions []*msgpb.MsgPosition) error {
	ret := _m.Called(ctx, info, seekPositions)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CollectionInfo, []*msgpb.MsgPosition) error); ok {
		r0 = rf(ctx, info, seekPositions)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelManager_StartReadCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartReadCollection'
type ChannelManager_StartReadCollection_Call struct {
	*mock.Call
}

// StartReadCollection is a helper method to define mock.On call
//  - ctx context.Context
//  - info *pb.CollectionInfo
//  - seekPositions []*msgpb.MsgPosition
func (_e *ChannelManager_Expecter) StartReadCollection(ctx interface{}, info interface{}, seekPositions interface{}) *ChannelManager_StartReadCollection_Call {
	return &ChannelManager_StartReadCollection_Call{Call: _e.mock.On("StartReadCollection", ctx, info, seekPositions)}
}

func (_c *ChannelManager_StartReadCollection_Call) Run(run func(ctx context.Context, info *pb.CollectionInfo, seekPositions []*msgpb.MsgPosition)) *ChannelManager_StartReadCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pb.CollectionInfo), args[2].([]*msgpb.MsgPosition))
	})
	return _c
}

func (_c *ChannelManager_StartReadCollection_Call) Return(_a0 error) *ChannelManager_StartReadCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_StartReadCollection_Call) RunAndReturn(run func(context.Context, *pb.CollectionInfo, []*msgpb.MsgPosition) error) *ChannelManager_StartReadCollection_Call {
	_c.Call.Return(run)
	return _c
}

// StopReadCollection provides a mock function with given fields: ctx, info
func (_m *ChannelManager) StopReadCollection(ctx context.Context, info *pb.CollectionInfo) error {
	ret := _m.Called(ctx, info)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.CollectionInfo) error); ok {
		r0 = rf(ctx, info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ChannelManager_StopReadCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopReadCollection'
type ChannelManager_StopReadCollection_Call struct {
	*mock.Call
}

// StopReadCollection is a helper method to define mock.On call
//  - ctx context.Context
//  - info *pb.CollectionInfo
func (_e *ChannelManager_Expecter) StopReadCollection(ctx interface{}, info interface{}) *ChannelManager_StopReadCollection_Call {
	return &ChannelManager_StopReadCollection_Call{Call: _e.mock.On("StopReadCollection", ctx, info)}
}

func (_c *ChannelManager_StopReadCollection_Call) Run(run func(ctx context.Context, info *pb.CollectionInfo)) *ChannelManager_StopReadCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*pb.CollectionInfo))
	})
	return _c
}

func (_c *ChannelManager_StopReadCollection_Call) Return(_a0 error) *ChannelManager_StopReadCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ChannelManager_StopReadCollection_Call) RunAndReturn(run func(context.Context, *pb.CollectionInfo) error) *ChannelManager_StopReadCollection_Call {
	_c.Call.Return(run)
	return _c
}

// NewChannelManager creates a new instance of ChannelManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChannelManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *ChannelManager {
	mock := &ChannelManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
