// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/milvus-io/milvus-sdk-go/v2/client"
	entity "github.com/milvus-io/milvus-sdk-go/v2/entity"
	mock "github.com/stretchr/testify/mock"
	"github.com/zilliztech/milvus-cdc/core/util"
)

// MilvusClientAPI is an autogenerated mock type for the MilvusClientAPI type
type MilvusClientAPI struct {
	util.CDCMark
	mock.Mock
}

// CreateCollection provides a mock function with given fields: ctx, schema, shardsNum, opts
func (_m *MilvusClientAPI) CreateCollection(ctx context.Context, schema *entity.Schema, shardsNum int32, opts ...client.CreateCollectionOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, schema, shardsNum)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.Schema, int32, ...client.CreateCollectionOption) error); ok {
		r0 = rf(ctx, schema, shardsNum, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDatabase provides a mock function with given fields: ctx, dbName
func (_m *MilvusClientAPI) CreateDatabase(ctx context.Context, dbName string) error {
	ret := _m.Called(ctx, dbName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dbName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateIndex provides a mock function with given fields: ctx, collName, fieldName, idx, async, opts
func (_m *MilvusClientAPI) CreateIndex(ctx context.Context, collName string, fieldName string, idx entity.Index, async bool, opts ...client.IndexOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, collName, fieldName, idx, async)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entity.Index, bool, ...client.IndexOption) error); ok {
		r0 = rf(ctx, collName, fieldName, idx, async, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreatePartition provides a mock function with given fields: ctx, collName, partitionName
func (_m *MilvusClientAPI) CreatePartition(ctx context.Context, collName string, partitionName string) error {
	ret := _m.Called(ctx, collName, partitionName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, collName, partitionName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteByPks provides a mock function with given fields: ctx, collName, partitionName, ids
func (_m *MilvusClientAPI) DeleteByPks(ctx context.Context, collName string, partitionName string, ids entity.Column) error {
	ret := _m.Called(ctx, collName, partitionName, ids)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, entity.Column) error); ok {
		r0 = rf(ctx, collName, partitionName, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DropCollection provides a mock function with given fields: ctx, collName
func (_m *MilvusClientAPI) DropCollection(ctx context.Context, collName string) error {
	ret := _m.Called(ctx, collName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, collName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DropDatabase provides a mock function with given fields: ctx, dbName
func (_m *MilvusClientAPI) DropDatabase(ctx context.Context, dbName string) error {
	ret := _m.Called(ctx, dbName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, dbName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DropIndex provides a mock function with given fields: ctx, collName, fieldName, opts
func (_m *MilvusClientAPI) DropIndex(ctx context.Context, collName string, fieldName string, opts ...client.IndexOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, collName, fieldName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...client.IndexOption) error); ok {
		r0 = rf(ctx, collName, fieldName, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DropPartition provides a mock function with given fields: ctx, collName, partitionName
func (_m *MilvusClientAPI) DropPartition(ctx context.Context, collName string, partitionName string) error {
	ret := _m.Called(ctx, collName, partitionName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, collName, partitionName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Insert provides a mock function with given fields: ctx, collName, partitionName, columns
func (_m *MilvusClientAPI) Insert(ctx context.Context, collName string, partitionName string, columns ...entity.Column) (entity.Column, error) {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, collName, partitionName)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 entity.Column
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...entity.Column) (entity.Column, error)); ok {
		return rf(ctx, collName, partitionName, columns...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, ...entity.Column) entity.Column); ok {
		r0 = rf(ctx, collName, partitionName, columns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.Column)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, ...entity.Column) error); ok {
		r1 = rf(ctx, collName, partitionName, columns...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadCollection provides a mock function with given fields: ctx, collName, async, opts
func (_m *MilvusClientAPI) LoadCollection(ctx context.Context, collName string, async bool, opts ...client.LoadCollectionOption) error {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, collName, async)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool, ...client.LoadCollectionOption) error); ok {
		r0 = rf(ctx, collName, async, opts...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReleaseCollection provides a mock function with given fields: ctx, collName
func (_m *MilvusClientAPI) ReleaseCollection(ctx context.Context, collName string) error {
	ret := _m.Called(ctx, collName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, collName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMilvusClientAPI interface {
	mock.TestingT
	Cleanup(func())
}

// NewMilvusClientAPI creates a new instance of MilvusClientAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMilvusClientAPI(t mockConstructorTestingTNewMilvusClientAPI) *MilvusClientAPI {
	mock := &MilvusClientAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
