name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - name: golangci-lint core
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./core
          args: --timeout=5m --out-format=colored-line-number ./...
          skip-cache: true
      - name: golangci-lint server
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          working-directory: ./server
          args: --timeout=5m --out-format=colored-line-number ./...
          skip-cache: true